# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

def build_title_info
  title = TitleInfo.new
  title.title = 'Poétry'
  title
end

def build_type_of_resource
  type_of_resource = TypeOfResource.new
  type_of_resource.content = 'text'
  type_of_resource
end

def build_genre
  genre = Genre.new
  genre.authority = 'aat'
  genre.content = 'aat theses'
  genre
end

def build_origin_info
  origin_info = OriginInfo.new
  origin_info.display_label = 'origin info'
  place = Place.new
  place_term = PlaceTerm.new
  place_term.content = 'USA'
  place.place_term = place_term
  origin_info.place = place
  origin_info
end
